Updated sync-update-drive to check to see if the drive is mounted, if not, it'll attempt to mount it. If it fails to mount it will now send an email to Chris and Alan.

diff --git a/sync-update-drive b/sync-update-drive
--- a/sync-update-drive
+++ b/sync-update-drive
@@ -1,7 +1,31 @@
 #!/bin/bash
-mount /mnt/update-drive
+UPDATE_DRIVE="/mnt/update-drive"
+TMP_FILE="/tmp/sync_drive.tmp"
+
+if [ -n "`mount |grep "$UPDATE_DRIVE"`" ]
+then
+	echo "$UPDATE_DRIVE already mounted"
+else
+	#Mount the device
+	mount /mnt/update-drive
+	
+	# Check to see if everything mounted OK
+	if [ $? -gt 0 ]
+	then 
+		echo "Failed to mount"
+		#Send an email
+		touch $TMP_FILE
+		echo "This message is generated by the $0 script." > $TMP_FILE
+		echo "**********************************************************************" >> $TMP_FILE
+		echo "" >> $TMP_FILE
+		echo "Failed to mount '$UPDATE_DRIVE'" >> $TMP_FILE
+		mailx -s "$0 backup failed - $(date)" alan.langley@naa.gov.au christopher.smart@naa.gov.au < $TMP_FILE
+		rm $TMP_FILE		
+
+		exit 1
+	fi
+fi
 rsync -av /data/ /mnt/update-drive/data/
 sync
-#umount /mnt/update-drive
+umount /mnt/update-drive
 #umount `cat /proc/mounts |grep 45b28ed7-1202-4d47-bfa9-d4a4ffa4375c |awk {'print $2'}`
-for x in `cat /proc/mounts |grep update-drive |awk {'print $2'}` ; do umount $x 2>$ERRORFILE ; done
